### ISSUE TITLE
beeline 删除 datamap

### ISSUE THREAD

**Issue by yfcck** [carbonlake/forum#3]
- CarbonData version: 1.6.1

- Spark/Hadoop version: 2.3.2/2.7.2

_在beeline中可以正常删除创建的mv datamap_
./beeline -u 'jdbc:hive2://host:10000/;transportMode=binary' --color=true

```js
use ods2;
drop datamap socol_cmdinfo808;
drop datamap socol_cmdinfo77;
drop datamap socol_cmdinfo78;

#drop main table
drop table socol_cmdinfo;

#drop database
drop database ods2;
```

_在spark-shell 中 show datamap 还存在已经在beeline里删除的mv datamap_

./spark-shell --master yarn --deploy-mode client --driver-memory 2g --num-executors 2 --executor-memory 2G --executor-cores 3

```js
import org.apache.spark.sql.SparkSession 
import org.apache.spark.sql.CarbonSession._ 
val carbon = SparkSession.builder().config("spark.sql.warehouse.dir", "hdfs://nameservice1/carbon").config("spark.sql.crossJoin.enabled", "true").getOrCreateCarbonSession("hdfs://nameservice1/carbon/data", "hdfs://nameservice1/carbon")

carbon.sql("show datamap").show

2019-12-04 16:22:09 ERROR DataMapStoreManager:300 - Error while registering schema
org.apache.spark.sql.AnalysisException: Table or view not found: `ods2`.`socol_cmdinfo`; line 3 pos 2;
'Project [UDF:preAgg() AS preAgg#0, 'a.id, 'a.imei, 'a.source]
+- 'SubqueryAlias a
   +- 'UnresolvedRelation `ods2`.`socol_cmdinfo`

        at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:86)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:84)
        at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:127)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:126)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:126)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:126)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:126)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:84)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:92)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:105)
        at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:57)
        at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:55)
        at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:47)
        at org.apache.spark.sql.CarbonSession.withProfiler(CarbonSession.scala:129)
        at org.apache.spark.sql.CarbonSession.sql(CarbonSession.scala:88)
        at org.apache.carbondata.mv.rewrite.SummaryDatasetCatalog$$anonfun$registerSchema$1.apply(SummaryDatasetCatalog.scala:112)
        at org.apache.carbondata.mv.rewrite.SummaryDatasetCatalog$$anonfun$registerSchema$1.apply(SummaryDatasetCatalog.scala:109)
        at org.apache.carbondata.mv.rewrite.SummaryDatasetCatalog.writeLock(SummaryDatasetCatalog.scala:84)
        at org.apache.carbondata.mv.rewrite.SummaryDatasetCatalog.registerSchema(SummaryDatasetCatalog.scala:109)
        at org.apache.carbondata.core.datamap.DataMapStoreManager.initializeDataMapCatalogs(DataMapStoreManager.java:297)
        at org.apache.carbondata.core.datamap.DataMapStoreManager.getDataMapCatalog(DataMapStoreManager.java:273)
        at org.apache.carbondata.mv.datamap.MVAnalyzerRule.apply(MVAnalyzerRule.scala:85)
        at org.apache.carbondata.mv.datamap.MVAnalyzerRule.apply(MVAnalyzerRule.scala:43)
        at org.apache.spark.sql.hive.CarbonAnalyzer.execute(CarbonAnalyzer.scala:46)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:103)
        at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:57)
        at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:55)
        at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:47)
        at org.apache.spark.sql.CarbonSession.withProfiler(CarbonSession.scala:129)
        at org.apache.spark.sql.CarbonSession.sql(CarbonSession.scala:88)
        at $line18.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:33)
        at $line18.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:38)
        at $line18.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:40)
        at $line18.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:42)
        at $line18.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:44)
        at $line18.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:46)
        at $line18.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:48)
        at $line18.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:50)
        at $line18.$read$$iw$$iw$$iw$$iw.<init>(<console>:52)
        at $line18.$read$$iw$$iw$$iw.<init>(<console>:54)
        at $line18.$read$$iw$$iw.<init>(<console>:56)
        at $line18.$read$$iw.<init>(<console>:58)
        at $line18.$read.<init>(<console>:60)
        at $line18.$read$.<init>(<console>:64)
        at $line18.$read$.<clinit>(<console>)
        at $line18.$eval$.$print$lzycompute(<console>:7)
        at $line18.$eval$.$print(<console>:6)
        at $line18.$eval.$print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:415)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:923)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
        at org.apache.spark.repl.Main$.doMain(Main.scala:76)
        at org.apache.spark.repl.Main$.main(Main.scala:56)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

+----------------+---------+--------------------+--------------------+--------------+-----------+
|     DataMapName|ClassName|    Associated Table|  DataMap Properties|DataMap Status|Sync Status|
+----------------+---------+--------------------+--------------------+--------------+-----------+
|socol_cmdinfo808|       mv|ods2.socol_cmdinf...|'full_refresh'='f...|      DISABLED|         NA|
| socol_cmdinfo77|       mv|ods2.socol_cmdinf...|'full_refresh'='f...|      DISABLED|         NA|
| socol_cmdinfo78|       mv|ods2.socol_cmdinf...|'full_refresh'='f...|       ENABLED|         NA|
+----------------+---------+--------------------+--------------------+--------------+-----------+

```

_通过spark-shell删除datamap_
```js
carbon.sql("drop datamap socol_cmdinfo77")

2019-12-04 15:08:53 AUDIT audit:72 - {"time":"December 4, 2019 3:08:53 PM CST","username":"hdfs","opName":"DROP DATAMAP","opId":"3877523789864808","opStatus":"START"}
2019-12-04 15:08:53 AUDIT audit:93 - {"time":"December 4, 2019 3:08:53 PM CST","username":"hdfs","opName":"DROP DATAMAP","opId":"3877523789864808","opStatus":"FAILED","opTime":"63 ms","table":"NA","extraInfo":{"Exception":"java.lang.IllegalArgumentException","Message":"requirement failed: Datamap socol_cmdinfo77 is not registered."}}
java.lang.IllegalArgumentException: requirement failed: Datamap socol_cmdinfo77 is not registered.
  at scala.Predef$.require(Predef.scala:224)
  at org.apache.carbondata.mv.rewrite.SummaryDatasetCatalog$$anonfun$unregisterSchema$1.apply(SummaryDatasetCatalog.scala:152)
  at org.apache.carbondata.mv.rewrite.SummaryDatasetCatalog$$anonfun$unregisterSchema$1.apply(SummaryDatasetCatalog.scala:149)
  at org.apache.carbondata.mv.rewrite.SummaryDatasetCatalog.writeLock(SummaryDatasetCatalog.scala:84)
  at org.apache.carbondata.mv.rewrite.SummaryDatasetCatalog.unregisterSchema(SummaryDatasetCatalog.scala:149)
  at org.apache.carbondata.core.datamap.DataMapStoreManager.unRegisterDataMapCatalog(DataMapStoreManager.java:262)
  at org.apache.carbondata.mv.datamap.MVDataMapProvider.cleanMeta(MVDataMapProvider.scala:94)
  at org.apache.spark.sql.execution.command.datamap.CarbonDropDataMapCommand.dropDataMapFromSystemFolder(CarbonDropDataMapCommand.scala:234)
  at org.apache.spark.sql.execution.command.datamap.CarbonDropDataMapCommand.processMetadata(CarbonDropDataMapCommand.scala:197)
  at org.apache.spark.sql.execution.command.AtomicRunnableCommand$$anonfun$run$3.apply(package.scala:146)
  at org.apache.spark.sql.execution.command.AtomicRunnableCommand$$anonfun$run$3.apply(package.scala:145)
  at org.apache.spark.sql.execution.command.Auditable$class.runWithAudit(package.scala:104)
  at org.apache.spark.sql.execution.command.AtomicRunnableCommand.runWithAudit(package.scala:141)
  at org.apache.spark.sql.execution.command.AtomicRunnableCommand.run(package.scala:145)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
  at org.apache.spark.sql.Dataset$$anonfun$6.apply(Dataset.scala:190)
  at org.apache.spark.sql.Dataset$$anonfun$6.apply(Dataset.scala:190)
  at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3259)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3258)
  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:190)
  at org.apache.spark.sql.CarbonSession$$anonfun$sql$1.apply(CarbonSession.scala:91)
  at org.apache.spark.sql.CarbonSession$$anonfun$sql$1.apply(CarbonSession.scala:90)
  at org.apache.spark.sql.CarbonSession.withProfiler(CarbonSession.scala:136)
  at org.apache.spark.sql.CarbonSession.sql(CarbonSession.scala:88)
  ... 53 elided

```

**Comment by jackylk** [comment]
这个好似是DataMap Schema的缓存问题，应该是DiskBasedDMSchemaStorageProvider.dataMapSchemas里对应的datamap没有清掉。

**Comment by zzcclp** [comment]
问题已经查清楚，麻烦写下结果并关闭，谢谢@hugess

**Comment by yfcck** [comment]
已解决

 beeline与spark session 的store_path 不一致

- [ ] CarbonData Thrift Server store_path

` hdfs://nameservice1/carbon/ods`

- [ ] Spark Session store_path

` hdfs://nameservice1/carbon`

```js
// - thrift server 与 spark session 的 store_path保持一致 
// - 确保 spark submit/thrift server 连接到hive metastore

// spark session
val carbon = SparkSession.
    builder().
    getOrCreateCarbonSession("hdfs://nameservice1/carbon/data", "hdfs://nameservice1/carbon")

// thrift server 
./spark-submit \
--class org.apache.carbondata.spark.thriftserver.CarbonThriftServer \
--master yarn \
--deploy-mode client \
/opt/lib/spark-2.3.2/carbonlib/apache-carbondata-1.6.1-bin-spark2.3.2-hadoop2.7.2.jar \
hdfs://nameservice1/carbon/data

// 删掉不一致的meta文件
hdfs dfs -rm -r -skipTrash <store_path>/_system/*

carbon.sql("show datamap")
+-----------+---------+----------------+------------------+--------------+-----------+
|DataMapName|ClassName|Associated Table|DataMap Properties|DataMap Status|Sync Status|
+-----------+---------+----------------+------------------+--------------+-----------+
+-----------+---------+----------------+------------------+--------------+-----------+
```
